#!/usr/bin/env php
<?php

// ==========================================
// 🔥 PATCH KHUSUS WINDOWS (XAMPP/LARAGON) 🔥
// ==========================================
if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
    if (!defined('SIGINT'))  define('SIGINT', 2);
    if (!defined('SIGTERM')) define('SIGTERM', 15);
    if (!defined('SIGHUP'))  define('SIGHUP', 1);

    if (!function_exists('posix_kill')) {
        function posix_kill($pid, $sig)
        {
            return false;
        }
    }

    if (!function_exists('posix_getpid')) {
        function posix_getpid()
        {
            return getmypid();
        }
    }
}

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__ . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__ . '/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
